apiVersion: v1
kind: Service
metadata:
  name: aux
  namespace: aux
  labels:
    app: aux
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kantox-challenge
spec:
  type: ClusterIP
  selector:
    app: aux
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
