#!/bin/bash
set -e

echo "🔐 Generating Kubernetes secrets from Terraform outputs..."

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/../infrastructure" && pwd)"
K8S_DIR="$(cd "$SCRIPT_DIR/../kubernetes" && pwd)"

cd "$INFRA_DIR"

if [ -f terraform.tfstate ]; then
  STATE_FILE="terraform.tfstate"
elif [ -d terraform.tfstate.d ]; then
  WORKSPACE=$(terraform workspace show 2>/dev/null || echo "")
  if [ -n "$WORKSPACE" ] && [ -f "terraform.tfstate.d/$WORKSPACE/terraform.tfstate" ]; then
    STATE_FILE="terraform.tfstate.d/$WORKSPACE/terraform.tfstate"
  else
    echo "❌ Error: terraform.tfstate not found."
    echo "Current workspace: $WORKSPACE"
    echo "Run 'terraform apply' first or select the correct workspace."
    exit 1
  fi
else
  echo "❌ Error: terraform.tfstate not found. Run 'terraform apply' first."
  exit 1
fi

echo "Using state file: $STATE_FILE"

echo "📥 Fetching credentials from Terraform output..."
CREDS=$(terraform output -json minikube_base_credentials 2>/dev/null)

if [ -z "$CREDS" ] || [ "$CREDS" = "null" ]; then
  echo "❌ Error: minikube_base_credentials output not found."
  echo "Make sure you've run 'terraform apply' successfully."
  exit 1
fi

ACCESS_KEY=$(echo "$CREDS" | jq -r '.access_key_id')
SECRET_KEY=$(echo "$CREDS" | jq -r '.secret_access_key')

ROLE_ARNS=$(terraform output -json service_role_arns 2>/dev/null)
AUX_ROLE_ARN=$(echo "$ROLE_ARNS" | jq -r '.aux_role_arn')

echo "✅ Credentials retrieved"
echo "   AUX Role: $AUX_ROLE_ARN"
echo "   Note: API service no longer requires AWS credentials (uses AUX service internally)"

mkdir -p "$K8S_DIR"

echo ""
echo "📝 Generating secret manifest for AUX namespace..."
cat > "$K8S_DIR/aux-aws-credentials-secret.yaml" <<EOF
# Generated by setup-k8s-secrets.sh
# DO NOT commit this file to git - contains sensitive credentials
apiVersion: v1
kind: Secret
metadata:
  name: aux-aws-credentials
  namespace: aux
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "$ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "$SECRET_KEY"
  AWS_ROLE_ARN: "$AUX_ROLE_ARN"
EOF

echo ""
echo "✅ Secret manifest generated in kubernetes/ folder"
echo ""
echo "Generated files:"
echo "  - kubernetes/aux-aws-credentials-secret.yaml"
echo ""
echo "Architecture note:"
echo "  API service = Public gateway (no AWS access)"
echo "  AUX service = Internal backend (handles all AWS operations)"
echo ""
echo "Next steps:"
echo "  1. Apply secret: kubectl apply -f kubernetes/aux-aws-credentials-secret.yaml"
echo "  2. Deploy your applications: kubectl apply -f kubernetes/"
echo ""
echo "⚠️  Remember: Do NOT commit aux-aws-credentials-secret.yaml to git"
echo ""
