apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kantox-challenge
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: kantox-challenge
    spec:
      containers:
      - name: api
        image: 035895024082.dkr.ecr.eu-west-1.amazonaws.com/kantox-api:sha-791611c
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # AWS Credentials from Secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: api-aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: api-aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              name: api-aws-credentials
              key: AWS_ROLE_ARN
        # Configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ENVIRONMENT
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_REGION
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: LOG_LEVEL
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: SERVICE_NAME
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
