apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kantox-challenge
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: kantox-challenge
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        # AUTO-UPDATED BY CI/CD - DO NOT MANUALLY EDIT
        # This value is dynamically replaced on every workflow run
        image: PLACEHOLDER.dkr.ecr.eu-west-1.amazonaws.com/kantox-api:sha-d9f8d7b
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        # AUX Service URL (internal service communication)
        - name: AUX_SERVICE_URL
          value: "http://aux.aux.svc.cluster.local:80"
        # Configuration from ConfigMap
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: LOG_LEVEL
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: SERVICE_NAME
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_REGION
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
