apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
  labels:
    app: api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: kantox-challenge
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
